<?php

declare(strict_types=1);

namespace BookSphere\App\Middleware;

use BookSphere\App\Core\Csrf;
use BookSphere\App\Core\Request;
use BookSphere\App\Core\Response;

use BookSphere\App\Core\Logger;

/**
 * CsrfMiddleware
 *
 * Rejects state-changing requests (POST) that do not carry a valid
 * CSRF token. The token is generated by the Csrf class and must be
 * present in every form as a hidden field named "_token".
 *
 * It exists so no controller has to remember to check CSRF itself:
 * routes that change data simply include this middleware.
 */
final class CsrfMiddleware
{
    public function __construct(
        private readonly Csrf $csrf,
        private readonly ?Logger $logger = null,
    ) {}

    /**
     * Validate the CSRF token, or stop the request with a 419 error.
     *
     * The token must arrive in the POST body (Request::post) - a
     * token carried in the query string is ignored, so a forged GET
     * link can never pass as a valid submission.
     */
    public function handle(Request $request, callable $next): mixed
    {
        $token = $request->post('_token') ?? $request->header('X-CSRF-TOKEN') ?? $request->header('X-CSRF-Token');

        if (!is_string($token) || !$this->csrf->validate($token)) {
            $this->logger?->warning('csrf.invalid_token', [
                'route'  => $_SERVER['REQUEST_URI'] ?? '',
                'method' => $_SERVER['REQUEST_METHOD'] ?? 'POST',
            ]);

            Response::error(419, 'Invalid form token.');
        }

        return $next();
    }
}
