<?php

declare(strict_types=1);

namespace BookSphere\App\Middleware;

use BookSphere\App\Core\Csrf;
use BookSphere\App\Core\Request;
use BookSphere\App\Core\Response;

/**
 * CsrfMiddleware
 *
 * Rejects state-changing requests (POST) that do not carry a valid
 * CSRF token. The token is generated by the Csrf class and must be
 * present in every form as a hidden field named "_token".
 *
 * It exists so no controller has to remember to check CSRF itself:
 * routes that change data simply include this middleware.
 */
final class CsrfMiddleware
{
    public function __construct(private readonly Csrf $csrf) {}

    /**
     * Validate the CSRF token, or stop the request with a 419 error.
     */
    public function handle(Request $request, callable $next): mixed
    {
        if (!$this->csrf->validate($request->input('_token'))) {
            Response::error(419, 'Invalid form token.');
        }

        return $next();
    }
}
